### ISSUE TITLE
Question: Necessity for threads in this gem

### ISSUE THREAD

**Issue by michiels** [alpha-netzilla/watson-conversation#1]
Hi there! I crossed this gem while trying to build a chatbot service in Ruby. The gem you created already works fine with the basics and I'd like to contribute to it or start my own Watson Ruby client version.

I noticed you're using threads in your code. Can you explain the motivation behind this? Since calls to the Watson API endpoints are synchronous POST calls so it seems that threading is not completely necessary.

Thanks very much in advance!

**Comment by alpha-netzilla** [comment]
I am deeply sorry for the late reply.
It's exactly as you said.

I will eliminate the thread in the gem when updating to the next version.
The gem is going to be a very simple design.

**Comment by alpha-netzilla** [comment]
Watson Conversation has been renamed to Watson Assistant.
I excluded threads at the new Watson Assistant library, according to the change of the name.
https://github.com/alpha-netzilla/watson-assistant

**Comment by alpha-netzilla** [comment]
Watson Conversation has been renamed to Watson Assistant.
I excluded the threads at the new Watson Assistant library, according to the change of the name.
https://github.com/alpha-netzilla/watson-assistant
